spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:53306/batch?useSSL=false&rewriteBatchedStatements=true&allowMultiQueries=true
            driver-class-name: com.mysql.jdbc.Driver
            username: root
            password: 123456
    batch:
        initialize-schema: always
        job:
            enabled: false


mybatis:
    mapper-locations: classpath:mapper/*.xml